In [1]:
import numpy as np
import glob
import tkinter as tk
from tkinter import filedialog 
import csv

In [2]:
root = tk.Tk()
root.withdraw()

file_path = filedialog.askdirectory()

In [3]:
path = file_path+'/*/*.csv'
files = glob.glob(path)
sep_path=[]
for line in files:
    temp = line.split('\\')
    temp[1] = float(temp[1])
    sep_path.append(temp)
sep_path = sorted(sep_path,key=lambda x: (x[2],x[1]))
files =[]
for i in range(0,len(sep_path)):
    temp = sep_path[i]
    files.append(temp[0]+'/'+str(int(temp[1]))+'/'+temp[2])

In [4]:
dt=[]
list_3d = []
for i in range(0,int(len(files)/8)):
    filename = sep_path[i*8][2]
    data=[]
    for j in range(0,8):
        file = files[i*8 + j]
        count = 0
        with open(file,'r',errors='ignore') as reader:
            for line in reader.readlines():
                if(count!=0):
                    data.append(line.split(',')[0:-1])
                else:
                    count=count+1
                    header = line.split(',')[0:-1]
    list_3d.append(data)
    dt.append([filename,header])

In [5]:
for i in range(0,len(list_3d)):
    
    with open(sep_path[0][0]+'/'+dt[i][0], 'w') as f:
      
    # using csv.writer method from CSV package
        write = csv.writer(f)
      
        write.writerow(dt[i][1])
        write.writerows(list_3d[i])

In [6]:
dt[i][1]

['TOWC (s)',
 'Week no',
 'Receiver Nano Seconds (ns)',
 'System Status-1',
 'System Status-2',
 'System Status-3',
 'Block Count',
 'Day',
 'Month',
 'Year',
 'Hour',
 'Minute',
 'Seconds',
 'External Clock Validity',
 'External Clock Frequency (Hz)']

In [22]:
import pandas as pd


SATB_L1 = pd.read_csv(r'D:\Documents\IIT INDORE PROJECT\NavIC\07_01_2019\WEDNESDAY\SATB_L1.csv')
SATB_L5 = pd.read_csv(r'D:\Documents\IIT INDORE PROJECT\NavIC\07_01_2019\WEDNESDAY\SATB_L5.csv')
SATB_S1 = pd.read_csv(r'D:\Documents\IIT INDORE PROJECT\NavIC\07_01_2019\WEDNESDAY\SATB_S1.csv')

In [23]:
SATB_L1

,TOWC (s),Week no,Receiver Nano Seconds (ns),System Status-1,System Status-2,System Status-3,Block Count,No of tracked channels,Acquisition status word1,Acquisition status word2,...,Tropo Delay-12 (m),Carrier Delay-12 (cycles),Satellite X Position-12 (m),Satellite Y Position-12 (m),Satellite Z Position-12 (m),Satellite X Velocity-12 (m/s),Satellite Y Velocity-12 (m/s),Satellite Z Velocity-12 (m/s),Range Residuals-12 (m),Satellite Clock Corrections-12 (ns)
0,259200,1011,0,1606123028,531103727,66260991,10169276,12,1721325145,2522502805,...,2.332068,-9.165522e+00,4.282055e+06,2.478260e+07,8.520173e+06,-249.738495,1069.818115,-2978.885742,0.0,89194.917550
1,259201,1011,0,1606123028,531103727,66260991,10169277,12,1721325145,2522502805,...,2.332207,7.359970e-01,4.281806e+06,2.478367e+07,8.517194e+06,-249.650894,1069.458740,-2979.067139,0.0,89194.915007
2,259202,1011,0,1606123028,531103727,66260991,10169278,12,1721325145,2522502805,...,2.332206,-1.651585e+01,4.281556e+06,2.478474e+07,8.514215e+06,-249.563324,1069.099243,-2979.248535,0.0,89194.912463
3,259203,1011,0,1606123028,531103727,66260991,10169279,12,1721325145,2522502805,...,2.332381,-8.427561e+00,4.281306e+06,2.478580e+07,8.511235e+06,-249.475815,1068.739746,-2979.429688,0.0,89194.909919
4,259204,1011,0,1606123028,531103727,66260991,10169280,12,1721325145,2522502805,...,2.332392,1.069321e+00,4.281057e+06,2.478687e+07,8.508256e+06,-249.388351,1068.380249,-2979.611084,0.0,89194.907376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86225,345595,1011,0,1606123028,531103727,66260991,10255671,12,1721325145,1448777365,...,15.799089,1.306699e+08,-1.021656e+07,1.971510e+07,-1.447534e+07,-1670.506592,800.818359,2324.856689,0.0,-18159.082526
86226,345596,1011,0,1606123028,531103727,66260991,10255672,12,1721325145,1448777365,...,15.793681,1.306681e+08,-1.021823e+07,1.971590e+07,-1.447302e+07,-1670.225464,800.744812,2325.166504,0.0,-18159.082867
86227,345597,1011,0,1606123028,531103727,66260991,10255673,12,1721325145,1448777365,...,15.788308,1.306662e+08,-1.021990e+07,1.971671e+07,-1.447069e+07,-1669.944214,800.671265,2325.476318,0.0,-18159.083209
86228,345598,1011,0,1606123028,531103727,66260991,10255674,12,1721325145,1448777365,...,15.782583,1.306644e+08,-1.022157e+07,1.971751e+07,-1.446836e+07,-1669.663086,800.597656,2325.785889,0.0,-18159.083551
86229,345599,1011,0,1606123028,531103727,66260991,10255675,12,1721325145,1448777365,...,15.776228,1.306626e+08,-1.022324e+07,1.971831e+07,-1.446604e+07,-1669.381958,800.523987,2326.095703,0.0,-18159.083893

In [3]:
SATB_L5

,TOWC (s),Week no,Receiver Nano Seconds (ns),System Status-1,System Status-2,System Status-3,Block Count,No of tracked channels,Acquisition status word1,Acquisition status word2,...,Tropo Delay-11 (m),Carrier Delay-11 (cycles),Satellite X Position-11 (m),Satellite Y Position-11 (m),Satellite Z Position-11 (m),Satellite X Velocity-11 (m/s),Satellite Y Velocity-11 (m/s),Satellite Z Velocity-11 (m/s),Range Residuals-11 (m),Satellite Clock Corrections-11 (ns)
0,259200,1011,0,1606123028,531103727,66260991,10169276,8,1469098,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,259201,1011,0,1606123028,531103727,66260991,10169277,8,1469098,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,259202,1011,0,1606123028,531103727,66260991,10169278,8,1469098,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,259203,1011,0,1606123028,531103727,66260991,10169279,8,1469098,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,259204,1011,0,1606123028,531103727,66260991,10169280,8,1469098,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86092,345595,1011,0,1606123028,531103727,66260991,10255671,8,1469098,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86093,345596,1011,0,1606123028,531103727,66260991,10255672,8,1469098,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86094,345597,1011,0,1606123028,531103727,66260991,10255673,8,1469098,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86095,345598,1011,0,1606123028,531103727,66260991,10255674,8,1469098,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86096,345599,1011,0,1606123028,531103727,66260991,10255675,8,1469098,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
SATB_S1

,TOWC (s),Week no,Receiver Nano Seconds (ns),System Status-1,System Status-2,System Status-3,Block Count,No of tracked channels,Acquisition status word1,Acquisition status word2,...,Tropo Delay-11 (m),Carrier Delay-11 (cycles),Satellite X Position-11 (m),Satellite Y Position-11 (m),Satellite Z Position-11 (m),Satellite X Velocity-11 (m/s),Satellite Y Velocity-11 (m/s),Satellite Z Velocity-11 (m/s),Range Residuals-11 (m),Satellite Clock Corrections-11 (ns)
0,259200,1011,0,1606123028,531103727,66260991,10169276,8,0,1469098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,259201,1011,0,1606123028,531103727,66260991,10169277,8,0,1469098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,259202,1011,0,1606123028,531103727,66260991,10169278,8,0,1469098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,259203,1011,0,1606123028,531103727,66260991,10169279,8,0,1469098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,259204,1011,0,1606123028,531103727,66260991,10169280,8,0,1469098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86062,345595,1011,0,1606123028,531103727,66260991,10255671,8,0,1469098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86063,345596,1011,0,1606123028,531103727,66260991,10255672,8,0,1469098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86064,345597,1011,0,1606123028,531103727,66260991,10255673,8,0,1469098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86065,345598,1011,0,1606123028,531103727,66260991,10255674,8,0,1469098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86066,345599,1011,0,1606123028,531103727,66260991,10255675,8,0,1469098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
SATB_L1

,TOWC (s),Week no,Receiver Nano Seconds (ns),System Status-1,System Status-2,System Status-3,Block Count,No of tracked channels,Acquisition status word1,Acquisition status word2,...,Tropo Delay-12 (m),Carrier Delay-12 (cycles),Satellite X Position-12 (m),Satellite Y Position-12 (m),Satellite Z Position-12 (m),Satellite X Velocity-12 (m/s),Satellite Y Velocity-12 (m/s),Satellite Z Velocity-12 (m/s),Range Residuals-12 (m),Satellite Clock Corrections-12 (ns)
0,259200,1011,0,1606123028,531103727,66260991,10169276,12,1721325145,2522502805,...,2.332068,-9.165522e+00,4.282055e+06,2.478260e+07,8.520173e+06,-249.738495,1069.818115,-2978.885742,0.0,89194.917550
1,259201,1011,0,1606123028,531103727,66260991,10169277,12,1721325145,2522502805,...,2.332207,7.359970e-01,4.281806e+06,2.478367e+07,8.517194e+06,-249.650894,1069.458740,-2979.067139,0.0,89194.915007
2,259202,1011,0,1606123028,531103727,66260991,10169278,12,1721325145,2522502805,...,2.332206,-1.651585e+01,4.281556e+06,2.478474e+07,8.514215e+06,-249.563324,1069.099243,-2979.248535,0.0,89194.912463
3,259203,1011,0,1606123028,531103727,66260991,10169279,12,1721325145,2522502805,...,2.332381,-8.427561e+00,4.281306e+06,2.478580e+07,8.511235e+06,-249.475815,1068.739746,-2979.429688,0.0,89194.909919
4,259204,1011,0,1606123028,531103727,66260991,10169280,12,1721325145,2522502805,...,2.332392,1.069321e+00,4.281057e+06,2.478687e+07,8.508256e+06,-249.388351,1068.380249,-2979.611084,0.0,89194.907376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86225,345595,1011,0,1606123028,531103727,66260991,10255671,12,1721325145,1448777365,...,15.799089,1.306699e+08,-1.021656e+07,1.971510e+07,-1.447534e+07,-1670.506592,800.818359,2324.856689,0.0,-18159.082526
86226,345596,1011,0,1606123028,531103727,66260991,10255672,12,1721325145,1448777365,...,15.793681,1.306681e+08,-1.021823e+07,1.971590e+07,-1.447302e+07,-1670.225464,800.744812,2325.166504,0.0,-18159.082867
86227,345597,1011,0,1606123028,531103727,66260991,10255673,12,1721325145,1448777365,...,15.788308,1.306662e+08,-1.021990e+07,1.971671e+07,-1.447069e+07,-1669.944214,800.671265,2325.476318,0.0,-18159.083209
86228,345598,1011,0,1606123028,531103727,66260991,10255674,12,1721325145,1448777365,...,15.782583,1.306644e+08,-1.022157e+07,1.971751e+07,-1.446836e+07,-1669.663086,800.597656,2325.785889,0.0,-18159.083551
86229,345599,1011,0,1606123028,531103727,66260991,10255675,12,1721325145,1448777365,...,15.776228,1.306626e+08,-1.022324e+07,1.971831e+07,-1.446604e+07,-1669.381958,800.523987,2326.095703,0.0,-18159.083893

In [4]:
import numpy as np
def cal2julian(yr,mn,dy):
    if mn < 1 | mn > 12:
        print('Invalid input month')
        return



    if dy < 1:
        print('Invalid input day')
        return
        
        
    if (mn == 2 and dy > 29) or (((mn== 3) or mn==5 or mn==9 or mn ==11)and dy > 30) or (dy > 31):
        print('Invalid input day');

        return


    if mn > 2:
        y = yr
        m = mn

    else:
        y = yr - 1
        m = mn + 12



    date1=4.5+31*(10+12*1582)

    date2=15.5+31*(10+12*1582) 

    date=dy+31*(mn+12*yr)

    if date <= date1:
        b = -2

    elif date >= date2:
        b = np.fix(y/400) - np.fix(y/100)

    else:
        print('Dates between October 5 & 15, 1582 do not exist')
        return



    if y > 0:
        jd = np.fix(365.25*y) + np.fix(30.6001*(m+1)) + b + 1720996.5 + dy
        return jd

    else:
        
        jd= np.fix(365.25*y-0.75) + np.fix(30.6001*(m+1)) + b + 1720996.5 + dy
        return jd

In [5]:
jdNavIC = cal2julian(1999,8,22)

In [14]:


def navic2jd(week,sow,rollover=0):
    nweek = week + 1024*rollover
    jd = jdNavIC + nweek*7 + (sow/3600)/24
    return jd

navic2jd(1011,259272)

2458492.5008333335

In [23]:
cal2julian(1999,8,22)

2451412.5

In [11]:
import math
def jd_to_date(jd):
   
   
    jd = jd + 0.5
    
    F, I = math.modf(jd)
    I = int(I)
    
    A = math.trunc((I - 1867216.25)/36524.25)
    
    if I > 2299160:
        B = I + 1 + A - math.trunc(A / 4.)
    else:
        B = I
        
    C = B + 1524
    
    D = math.trunc((C - 122.1) / 365.25)
    
    E = math.trunc(365.25 * D)
    
    G = math.trunc((C - E) / 30.6001)
    
    day = C - E + F - math.trunc(30.6001 * G)
    
    if G < 13.5:
        month = G - 1
    else:
        month = G - 13
        
    if month > 2.5:
        year = D - 4716
    else:
        year = D - 4715
    Day= int(day)
    Hour = (day-int(day))*24
    Minute = (Hour-int(Hour))*60
    sec = (Minute-int(Minute))*60
        
    return year, month, Day,Hour,Minute,sec

In [33]:
x = jd_to_date(2458492.50083333)

In [34]:
x

(2019, 1, 9, 0.019999925047159195, 1.1999955028295517, 11.999730169773102)